# SITE CONFIGURATION
baseurl: "/"
url: "https://brandonsvoid.com"

# THEME-SPECIFIC CONFIGURATION
title: Brandon's Void                                # site's title
tagline: "Come on in"
description: "This is my own personal void that I like screaming into. Visit if you'd like to listen in."      # used by search engines
avatar: assets/img/moon_icon.webp                        # Empty for no avatar in navbar
favicon: assets/favicon.ico                             # Icon displayed in the tab

#Jekyll SEO stuff
twitter:
  username: BrandonFordMO
  card: summary
author: brandon
logo: assets/img/moon_icon.webp 
social: 
  name: Brandon Ford
  links:
    - https://twitter.com/BrandonFordMO
    - https://www.linkedin.com/in/brandon-ford-1439a2207/
    - https://github.com/brandonrford

# Header and footer text
header_text: "Brandon's Void"  # Change Blog header text
header_feature_image: assets/img/header.jpg
footer_text: >
  <a href="/licenses/">Copyright 2021 Brandon Ford</a>. Created using the <a href="https://github.com/sylhare/Type-on-Strap">Type on Strap</a> theme. <a href="/sitemap/">Sitemap</a>. <a href="/privacy/">Privacy and Cookie Policy</a>.

# Blog
excerpt: true                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true

# Features
# More in the _data folder for share buttons, author and language
# For layout customization, go to the "_sass > base" folder, and check "_variables.scss"
katex:                                              # Enable if using math markup
mermaid:                                            # Enable mermaid-js for sequence and diagrams
google_analytics: G-WZ4J8H6Q3N                                      # Tracking ID, e.g. "UA-000000-01"
cookie_consent: true                                   # To respect the usage of cookies
color_theme: dark                                       # auto, dark or light

# PAGINATION
paginate: 20
paginate_path: "/blog/page:num"

# BUILD SETTINGS
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]
exclude: [".jekyll-cache", ".idea", "vendor/*", "assets/node_modules/*"]

# theme: type-on-strap                                  # if using the theme as a jekyll theme gem
remote_theme: sylhare/Type-on-Strap                     # If using as a remote_theme in github
